import type { Evidence } from '@/types'

export const evidenceItems: Evidence[] = [
  {
    id: 'ev-001',
    title: 'SME supply chain award letters',
    type: 'Document',
    status: 'approved',
    uploadedAt: '2026-02-18',
    projectId: 'hawthorne-health-hub',
    actionId: 'haw-local-spend',
    owner: 'Procurement',
  },
  {
    id: 'ev-002',
    title: 'Apprenticeship start confirmations',
    type: 'Spreadsheet',
    status: 'received',
    uploadedAt: '2026-01-22',
    projectId: 'hawthorne-health-hub',
    actionId: 'haw-apprenticeships',
    owner: 'HR',
  },
  {
    id: 'ev-003',
    title: 'Retrofit pilot completion report',
    type: 'Report',
    status: 'received',
    uploadedAt: '2026-03-05',
    projectId: 'hawthorne-health-hub',
    actionId: 'haw-retrofit',
    owner: 'Sustainability',
  },
  {
    id: 'ev-004',
    title: 'Volunteer day attendance sheets',
    type: 'Attendance',
    status: 'approved',
    uploadedAt: '2026-03-08',
    projectId: 'rivergate-regeneration',
    actionId: 'riv-volunteering',
    owner: 'Community',
  },
  {
    id: 'ev-005',
    title: 'Careers clinic feedback summary',
    type: 'Survey',
    status: 'approved',
    uploadedAt: '2026-03-01',
    projectId: 'rivergate-regeneration',
    actionId: 'riv-careers',
    owner: 'Learning',
  },
  {
    id: 'ev-006',
    title: 'Community grant allocation list',
    type: 'Document',
    status: 'approved',
    uploadedAt: '2025-06-05',
    projectId: 'elm-court-refurbishment',
    actionId: 'elm-grants',
    owner: 'Community',
  },
  {
    id: 'ev-007',
    title: 'Digital inclusion device receipts',
    type: 'Invoice',
    status: 'received',
    uploadedAt: '2025-05-30',
    projectId: 'elm-court-refurbishment',
    actionId: 'elm-digital',
    owner: 'Learning',
  },
  {
    id: 'ev-008',
    title: 'Biodiversity planting inspection photos',
    type: 'Photo',
    status: 'action-needed',
    uploadedAt: '2026-02-28',
    projectId: 'pinehurst-green',
    actionId: 'pine-biodiversity',
    owner: 'Environment',
  },
  {
    id: 'ev-009',
    title: 'Wellbeing clinic attendance log',
    type: 'Attendance',
    status: 'approved',
    uploadedAt: '2026-03-16',
    projectId: 'northbank-community-hub',
    actionId: 'northbank-wellbeing',
    owner: 'Health',
  },
  {
    id: 'ev-010',
    title: 'Training completion certificates',
    type: 'Certificates',
    status: 'received',
    uploadedAt: '2026-02-20',
    projectId: 'northbank-community-hub',
    actionId: 'northbank-training',
    owner: 'Learning',
  },
]

export const evidenceStorage = {
  list: () => evidenceItems,
  getByProject: (projectId: string) => evidenceItems.filter((item) => item.projectId === projectId),
}
